import json
from pathlib import Path

nodes = [
    {'id': 'mainactivity_mainactivity', 'label': 'MainActivity', 'file_type': 'code', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\MainActivity.kt', 'source_location': '65-104', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'dashboardviewmodel_dashboardviewmodel', 'label': 'DashboardViewModel', 'file_type': 'code', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\viewmodel\\DashboardViewModel.kt', 'source_location': '58-319', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'singboxremote_singboxremote', 'label': 'SingBoxRemote', 'file_type': 'code', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\ipc\\SingBoxRemote.kt', 'source_location': '41-319', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'singboxipchub_singboxipchub', 'label': 'SingBoxIpcHub', 'file_type': 'code', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\ipc\\SingBoxIpcHub.kt', 'source_location': '27-279', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'vpnstatestore_vpnstatestore', 'label': 'VpnStateStore', 'file_type': 'code', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\ipc\\VpnStateStore.kt', 'source_location': '10-259', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'configrepository_configrepository_arch', 'label': 'ConfigRepository Runtime Orchestrator', 'file_type': 'code', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\repository\\ConfigRepository.kt', 'source_location': '61-357', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'singboxservice_singboxservice_arch', 'label': 'SingBoxService Runtime Service', 'file_type': 'code', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\service\\SingBoxService.kt', 'source_location': '64-319', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'boxwrappermanager_boxwrappermanager', 'label': 'BoxWrapperManager', 'file_type': 'code', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\service\\SingBoxService.kt', 'source_location': '27-29', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'uivpn_process_split', 'label': 'UI and VPN Process Split', 'file_type': 'document', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\MainActivity.kt', 'source_location': '117-145', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'dual_channel_state_sync', 'label': 'Dual Channel State Sync', 'file_type': 'document', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\ipc\\SingBoxRemote.kt', 'source_location': '125-201', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
    {'id': 'runtime_config_generation', 'label': 'Runtime Config Generation', 'file_type': 'document', 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\repository\\ConfigRepository.kt', 'source_location': '92-233', 'source_url': None, 'captured_at': None, 'author': None, 'contributor': None},
]

EX = 'EXTRACTED'
IN = 'INFERRED'
edges = [
    {'source': 'mainactivity_mainactivity', 'target': 'dashboardviewmodel_dashboardviewmodel', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\MainActivity.kt', 'source_location': '133-145', 'weight': 1.0},
    {'source': 'mainactivity_mainactivity', 'target': 'singboxremote_singboxremote', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\MainActivity.kt', 'source_location': '116-145', 'weight': 1.0},
    {'source': 'mainactivity_mainactivity', 'target': 'uivpn_process_split', 'relation': 'rationale_for', 'confidence': IN, 'confidence_score': 0.86, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\MainActivity.kt', 'source_location': '116-145', 'weight': 1.0},
    {'source': 'dashboardviewmodel_dashboardviewmodel', 'target': 'configrepository_configrepository_arch', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\viewmodel\\DashboardViewModel.kt', 'source_location': '64-65,93-145', 'weight': 1.0},
    {'source': 'dashboardviewmodel_dashboardviewmodel', 'target': 'singboxremote_singboxremote', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\viewmodel\\DashboardViewModel.kt', 'source_location': '25,107-119,253-319', 'weight': 1.0},
    {'source': 'dashboardviewmodel_dashboardviewmodel', 'target': 'uivpn_process_split', 'relation': 'conceptually_related_to', 'confidence': IN, 'confidence_score': 0.72, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\viewmodel\\DashboardViewModel.kt', 'source_location': '107-119,273-319', 'weight': 1.0},
    {'source': 'singboxremote_singboxremote', 'target': 'vpnstatestore_vpnstatestore', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\ipc\\SingBoxRemote.kt', 'source_location': '194-201,245-268', 'weight': 1.0},
    {'source': 'singboxremote_singboxremote', 'target': 'dual_channel_state_sync', 'relation': 'rationale_for', 'confidence': IN, 'confidence_score': 0.90, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\ipc\\SingBoxRemote.kt', 'source_location': '125-201,245-318', 'weight': 1.0},
    {'source': 'singboxipchub_singboxipchub', 'target': 'vpnstatestore_vpnstatestore', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\ipc\\SingBoxIpcHub.kt', 'source_location': '104-105,141-158', 'weight': 1.0},
    {'source': 'singboxipchub_singboxipchub', 'target': 'dual_channel_state_sync', 'relation': 'rationale_for', 'confidence': IN, 'confidence_score': 0.88, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\ipc\\SingBoxIpcHub.kt', 'source_location': '133-166,169-235', 'weight': 1.0},
    {'source': 'singboxservice_singboxservice_arch', 'target': 'configrepository_configrepository_arch', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\service\\SingBoxService.kt', 'source_location': '21,70-176', 'weight': 1.0},
    {'source': 'singboxservice_singboxservice_arch', 'target': 'singboxipchub_singboxipchub', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\service\\SingBoxService.kt', 'source_location': '17', 'weight': 1.0},
    {'source': 'singboxservice_singboxservice_arch', 'target': 'vpnstatestore_vpnstatestore', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\service\\SingBoxService.kt', 'source_location': '18', 'weight': 1.0},
    {'source': 'singboxservice_singboxservice_arch', 'target': 'boxwrappermanager_boxwrappermanager', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\service\\SingBoxService.kt', 'source_location': '27,174-176', 'weight': 1.0},
    {'source': 'singboxservice_singboxservice_arch', 'target': 'uivpn_process_split', 'relation': 'rationale_for', 'confidence': IN, 'confidence_score': 0.84, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\service\\SingBoxService.kt', 'source_location': '64-176', 'weight': 1.0},
    {'source': 'configrepository_configrepository_arch', 'target': 'runtime_config_generation', 'relation': 'rationale_for', 'confidence': IN, 'confidence_score': 0.91, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\repository\\ConfigRepository.kt', 'source_location': '92-233', 'weight': 1.0},
    {'source': 'configrepository_configrepository_arch', 'target': 'singboxremote_singboxremote', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\repository\\ConfigRepository.kt', 'source_location': '14', 'weight': 1.0},
    {'source': 'configrepository_configrepository_arch', 'target': 'vpnstatestore_vpnstatestore', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\repository\\ConfigRepository.kt', 'source_location': '15', 'weight': 1.0},
    {'source': 'configrepository_configrepository_arch', 'target': 'singboxservice_singboxservice_arch', 'relation': 'references', 'confidence': EX, 'confidence_score': 1.0, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\repository\\ConfigRepository.kt', 'source_location': '18-19', 'weight': 1.0},
    {'source': 'configrepository_configrepository_arch', 'target': 'dual_channel_state_sync', 'relation': 'shares_data_with', 'confidence': IN, 'confidence_score': 0.69, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\repository\\ConfigRepository.kt', 'source_location': '14-19', 'weight': 1.0},
]

hyperedges = [
    {'id': 'ui_runtime_control_flow', 'label': 'UI Runtime Control Flow', 'nodes': ['mainactivity_mainactivity', 'dashboardviewmodel_dashboardviewmodel', 'singboxremote_singboxremote', 'singboxservice_singboxservice_arch', 'configrepository_configrepository_arch'], 'relation': 'participate_in', 'confidence': 'INFERRED', 'confidence_score': 0.83, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\MainActivity.kt'},
    {'id': 'ipc_state_sync_flow', 'label': 'IPC State Sync Flow', 'nodes': ['singboxremote_singboxremote', 'singboxipchub_singboxipchub', 'vpnstatestore_vpnstatestore', 'dual_channel_state_sync'], 'relation': 'form', 'confidence': 'INFERRED', 'confidence_score': 0.88, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\ipc\\SingBoxRemote.kt'},
    {'id': 'config_runtime_flow', 'label': 'Config Runtime Flow', 'nodes': ['configrepository_configrepository_arch', 'runtime_config_generation', 'singboxservice_singboxservice_arch', 'boxwrappermanager_boxwrappermanager'], 'relation': 'participate_in', 'confidence': 'INFERRED', 'confidence_score': 0.81, 'source_file': 'app\\src\\main\\java\\com\\kunk\\singbox\\repository\\ConfigRepository.kt'},
]

payload = {'nodes': nodes, 'edges': edges, 'hyperedges': hyperedges, 'input_tokens': 0, 'output_tokens': 0}
Path('C:\\Users\\33039\\Desktop\\KunBox\\.graphify_rebuild_semantic.py').write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding='utf-8')
